BookShopping_Project/Areas/Admin/Controllers/CategoryController.cs
using BookShopping_Project.DataAccess.Data;
using BookShopping_Project.Models;
using BookShopping_Project.Utility;
using BookShoppinhg_Project.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace BookShopping_Project.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles =SD.Role_Admin)]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Upsert(int? id)
        {
            Category category = new Category();
            if (id == null)
                return View(category);
            category = _unitOfWork.Category.Get(id.GetValueOrDefault());
            return View(category);
        }
        [HttpPost]
        public IActionResult Upsert (Category category)
        {
            if (category == null)
                return NotFound();
            if (!ModelState.IsValid)
                return View(category);
            if (category.id == 0)
                _unitOfWork.Category.Add(category);
            else
                _unitOfWork.Category.update(category);
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }
        #region APIs
        [HttpGet]
        public IActionResult GetAll()
        {
            var CategoryList = _unitOfWork.Category.GetAll();
            return Json(new { Data = CategoryList });
        }
        [HttpDelete]
        public IActionResult Delete(int Id)
        {
            var CategoryInDb = _unitOfWork.Category.Get(Id);
            if (CategoryInDb == null)
                return Json(new { success = false, message = "Error while delete data!!" });
            _unitOfWork.Category.remove(CategoryInDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Data Deleted Successfully!!" });
        }

        #endregion
    }

}

BookShopping_Project/Areas/Admin/Controllers/CompanyController.cs
using BookShopping_Project.Models;
using BookShopping_Project.Utility;
using BookShoppinhg_Project.DataAccess.Repository;
using BookShoppinhg_Project.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookShopping_Project.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles =SD.Role_Admin+","+SD.Role_Employee)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Upsert(int? id)
        {
            Company company = new Company();
            if (id == null)
                return View(company);
            company = _unitOfWork.company.Get(id.GetValueOrDefault());
            return View(company);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Company company)
        {
            if (company == null)
                return NotFound();
            if (!ModelState.IsValid)
                return View(company);
            if (company.Id == 0)
                _unitOfWork.company.Add(company);
            else
                _unitOfWork.company.Update(company);
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }            
        

        #region APIs
        [HttpGet]
        public IActionResult GetAll()
        {
            var CompanyList = _unitOfWork.company.GetAll();
            return Json(new { data = CompanyList });
        }
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var CompanyInDb = _unitOfWork.company.Get(id);
            if (CompanyInDb == null)
                return (Json(new { success = false, message = "Error while Deleting data!!!" }));
            else
                _unitOfWork.company.remove(CompanyInDb);
            _unitOfWork.Save();
            return (Json(new { success = true, message = "Data Deleted Successfully!!!" }));
        }
        #endregion
    }
}

BookShopping_Project/Areas/Admin/Controllers/ProductController.cs
using BookShopping_Project.DataAccess.Data;
using BookShopping_Project.Models;
using BookShopping_Project.Models.ViewModels;
using BookShoppinhg_Project.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BookShopping_Project.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller 
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Upsert(int? id)
        {
            ProductVM productVM = new ProductVM()
            {
                product = new Product(),
                CategoryList = _unitOfWork.Category.GetAll().Select(cl => new SelectListItem()
                {
                    Text = cl.name,
                    Value = cl.id.ToString()
                }),
                CoverTypeList = _unitOfWork.CoverType.GetAll().Select(ct => new SelectListItem()
                {
                    Text = ct.name,
                    Value = ct.id.ToString()
                })
            };
            if (id == null)
                return View(productVM);
            //productVM.product = _unitOfWork.Product.FirstorDefault(p => p.id == id.GetValueOrDefault(), IncludeProperties: "Category,CoverType");
            productVM.product = _unitOfWork.Product.Get(id.GetValueOrDefault());
            return View(productVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM productVM)
        {
            if (ModelState.IsValid)
            {
                var WebRootPath = _webHostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    var fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(WebRootPath, @"Images/Products");
                    var Extension = Path.GetExtension(files[0].FileName);
                    if (productVM.product.id != 0)
                    {
                        var ImageExist = _unitOfWork.Product.Get(productVM.product.id).ImageUrl;
                        productVM.product.ImageUrl = ImageExist;
                    }
                    if (productVM.product.ImageUrl != null)
                    {
                        var ImagePath = Path.Combine(WebRootPath, productVM.product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(ImagePath))
                        {
                            System.IO.File.Delete(ImagePath);
                        }
                    }
                    using (var FileStream = new FileStream(Path.Combine(uploads, fileName + Extension), FileMode.Create))
                    {
                        files[0].CopyTo(FileStream);
                    }
                    productVM.product.ImageUrl = @"/Images/Products/" + fileName + Extension;
                }

                else
                {
                    if (productVM.product.id != 0)
                    {
                        var ImageExists = _unitOfWork.Product.Get(productVM.product.id).ImageUrl;
                        productVM.product.ImageUrl = ImageExists;
                    }
                }
 
                if (productVM.product.id == 0)
                    _unitOfWork.Product.Add(productVM.product);
                else
                    _unitOfWork.Product.update(productVM.product);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }

            else
            {
                productVM = new ProductVM()
                {
                    CategoryList = _unitOfWork.Category.GetAll().Select(cl => new SelectListItem()
                    {
                        Text = cl.name,
                        Value = cl.id.ToString()
                    }),
                    CoverTypeList = _unitOfWork.Category.GetAll().Select(ct => new SelectListItem()
                    {
                        Text = ct.name,
                        Value = ct.id.ToString()
                    })
                };
                if (productVM.product.id != 0)
                {
                    productVM.product = _unitOfWork.Product.Get(productVM.product.id);
                
            }
            return View(productVM);
}
            
        }


        #region APIs
        [HttpGet]
        public IActionResult GetAll()
        {
            var ProductList = _unitOfWork.Product.GetAll(IncludeProperties: "Category,CoverType");
            return Json(new { data = ProductList });
        }
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var ProductInDb = _unitOfWork.Product.Get(id);
            if (ProductInDb == null)
                return Json(new { success = false, message = "Error while Deleting Data!!" });
            if (ProductInDb.ImageUrl == "")
            {
                var WebRootPath = _webHostEnvironment.WebRootPath;
                var ImagePath = Path.Combine(WebRootPath, ProductInDb.ImageUrl.TrimStart('\\'));
                if (System.IO.File.Exists(ImagePath)){
                    System.IO.File.Delete(ImagePath);
                }
            }
            _unitOfWork.Product.remove(ProductInDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Data Deleted Successfully!!" });
        }
        #endregion
    }
}

BookShopping_Project/Areas/Admin/Controllers/UserController.cs
using BookShopping_Project.DataAccess.Data;
using BookShopping_Project.Models;
using BookShopping_Project.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookShopping_Project.Areas.Admin.Controllers

{
    [Area("Admin")]
    

    public class UserController : Controller
    {
        private readonly ApplicationDbContext _context;
        public UserController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        #region APIs
       [HttpGet]
           public IActionResult GetAll()
        {
            var UserList = _context.applicationUsers.Include(c => c.company).ToList();
            var userrole = _context.UserRoles.ToList();
            var roles = _context.Roles.ToList();
            foreach(var User in UserList)
            {
                var RoleId = userrole.FirstOrDefault(u => u.UserId == User.Id).RoleId;
                User.Role = roles.FirstOrDefault(r => r.Id == RoleId).Name;
                if (User.company == null)
                {
                    User.company = new Company()
                    {
                        Name = ""
                    };
                }
            }
            if (!User.IsInRole(SD.Role_Admin))
            {
                var UserAdmin = UserList.FirstOrDefault(u => u.Role == SD.Role_Admin);
                UserList.Remove(UserAdmin);
            }
            return Json(new { data = UserList });
        }
        [HttpPost]
        public IActionResult lockUnlock([FromBody] string id)
        {
            bool islocked = false;
            var UserInDb = _context.applicationUsers.FirstOrDefault(u => u.Id == id);
            if (UserInDb == null)
                return Json(new { success = false, message = "Error while lock and unlock the User!!" });
            if(UserInDb!=null && UserInDb.LockoutEnd > DateTime.Now)
            {
                UserInDb.LockoutEnd = DateTime.Now;
                islocked = false;
            }
            else
            {
                UserInDb.LockoutEnd = DateTime.Now.AddYears(20);
                islocked = true;
            }
            _context.SaveChanges();
            return Json(new { success = true, message = islocked == true ? "User Successfully Locked" : "User Successfully Unlocked" });
        }
        #endregion
    }
}

BookShopping_Project/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Create</button>
    </div>
    <div class="col row">
        <a class="btn btn-success form-control" asp-action="Index">Back To List</a>
    </div>
</div>

BookShopping_Project/Views/Shared/_EditAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Update</button>
    </div>
    <div class="col row">
        <a class="btn btn-success form-control" asp-action="Index">Back To List</a>
    </div>
</div>

BookShopping_Project/Views/Shared/_Layout.cshtml
@using BookShopping_Project.Utility
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor httpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookShopping_Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Book Shopping</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Content Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category List</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">Cover Type</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                </div>
                            </li>

                        }

                        @if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Employee))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Company/User
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">User</a>
                                </div>
                            </li>
                        }
                        @if (httpContextAccessor.HttpContext.Session.GetInt32(SD.Ss_Session) != null)
                        {
                            <li>
                                <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                    @{
                                        var Count = httpContextAccessor.HttpContext.Session.GetInt32(SD.Ss_Session);
                                    }
                                    <i class="fas fa-shopping-cart"></i>&nbsp; (@Count)
                                </a>
                            </li>
                        }
                        else
                        {
                            <li>
                                <a class="nav-link">
                                    <i class="fas fa-shopping-cart"></i>&nbsp;(0)
                                </a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BookShopping_Project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>